version: "2.4"
services:
  sensor1:
    build:
      context: Cliente/
      dockerfile: Dockerfile
    
    networks:
      - red-app
    command: bash -c "cd /app && java -jar Cliente.jar 1"

  sensor2:
    build:
      context: Cliente/
      dockerfile: Dockerfile

    networks:
      - red-app
    command: bash -c "cd /app && java -jar Cliente.jar 2"

networks:  
  red-app:   
